FROM node:lts-alpine

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN yarn install
RUN yarn global add @vue/cli

# build app for production with minification
EXPOSE 8000
CMD [ "env", "VUE_APP_API_URL=http://0.0.0.0:5000", "yarn", "serve", "--port", "8000" ]