version:  '3'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile_dev_staging
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8002:8000'